### ISSUE TITLE
Dependency update required for Docker extension 

### ISSUE THREAD

**Issue by fiveisprime** [tiaanduplessis/vs-code-js-hacker-pack#7]
Hi!

I just wanted to give you a heads up that the Docker extension has been migrated to a new publisher and, you'll need to update your dependency so it will install correctly.

Please update `"PeterJausovec.vscode-docker"` to `"ms-azuretools.vscode-docker"` to ensure the extension is installed correctly.

Thanks and sorry for the inconvenience.

**Comment by tiaanduplessis** [comment]
@fiveisprime thanks for letting me know! Will update as soon as I get a chance 👍

**Comment by tiaanduplessis** [comment]
Updated with the latest version
